plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs32.github.io 
baseurl: "/s19"

course: "CS32"
qtr: "S19"
quarter: "Spring 2019"
piazza_url: piazza.com/ucsb/spring2019/cs32s19
gauchospace_course_page:
gradescope_class_url: https://www.gradescope.com/courses/46388

ta_list: "Ran, Yuke"
ta_list_full: "Ran Liu, Yuke Wang"
mentors_list: "George Kripac, Dylan Kupsh, Garrett Lee, Andrew Luo"
discussion_section_times: "12pm, 1pm, 2pm, and 3pm"

github_url: https://github.com/ucsb-cs32/s19
mentor_url:

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048

submit_cs_course:

start_week: 1
start_date: 2019-03-31 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true
sections: "12pm,1pm, 2pm, 3pm"

cal_dates: >
  [
  {"label":"First day of Spring Quarter", "date":"2019-04-01" },
  {"label":"Univ Holiday: Memorial Day", "date":"2019-05-27" },
  {"label":"Last day of instruction", "date":"2019-06-07" },
  {"label":"Finals Begin", "date":"2019-06-08" },
  {"label":"Finals End", "date":"2018-06-14" },
  {"label":"Last day to drop (11pm)", "date":"2019-04-26" }
  ]


kramdown:
   parse_block_html: true
   default_lang: python

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
